name: Docker Image CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.13.0]
    steps:
    - uses: actions/checkout@v2
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Local Configurations
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        echo "Finished setting up the env variables"
    - name: build
      run: |
        echo "Authenticating docker"
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        echo "Building docker image"
        docker build -t amit305/docker-manul-deploy:${GITHUB_REF##*/} .
        echo "Pushing the amit305/docker-manual-deploy:${GITHUB_REF##*/} to the Docker"
        docker push amit305/docker-manual-deploy:${GITHUB_REF##*/}
